import { AgentSpec, AgentRole } from './schema.js';
import { generateId } from '@apex/shared';

const NOW = '2026-06-15T00:00:00.000Z';

export const DEFAULT_AGENTS: AgentSpec[] = [
  {
    agentId: 'agent_orchestrator',
    name: 'orchestrator',
    role: 'ORCHESTRATOR' as AgentRole,
    status: 'IDLE',
    enabled: true,
    capabilities: {
      planning: true,
      coding: false,
      testing: false,
      reviewing: false,
      security: false,
      orchestration: true,
    },
    preferredProfile: 'interactive',
    preferredModel: 'default',
    loadFactor: 0,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    agentId: 'agent_brain',
    name: 'brain',
    role: 'BRAIN' as AgentRole,
    status: 'IDLE',
    enabled: true,
    capabilities: {
      planning: true,
      coding: false,
      testing: false,
      reviewing: false,
      security: false,
      orchestration: false,
    },
    preferredProfile: 'interactive',
    preferredModel: 'default',
    loadFactor: 0,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    agentId: 'agent_planner',
    name: 'planner',
    role: 'PLANNER' as AgentRole,
    status: 'IDLE',
    enabled: true,
    capabilities: {
      planning: true,
      coding: false,
      testing: false,
      reviewing: false,
      security: false,
      orchestration: false,
    },
    preferredProfile: 'interactive',
    preferredModel: 'default',
    loadFactor: 0,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    agentId: 'agent_engine',
    name: 'engine',
    role: 'ENGINE' as AgentRole,
    status: 'IDLE',
    enabled: true,
    capabilities: {
      planning: false,
      coding: true,
      testing: true,
      reviewing: false,
      security: false,
      orchestration: false,
    },
    preferredProfile: 'execution',
    preferredModel: 'default',
    loadFactor: 0,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    agentId: 'agent_code_reviewer',
    name: 'code-reviewer',
    role: 'CODE_REVIEWER' as AgentRole,
    status: 'IDLE',
    enabled: true,
    capabilities: {
      planning: false,
      coding: true,
      testing: false,
      reviewing: true,
      security: false,
      orchestration: false,
    },
    preferredProfile: 'review',
    preferredModel: 'default',
    loadFactor: 0,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    agentId: 'agent_security_reviewer',
    name: 'security-reviewer',
    role: 'SECURITY_REVIEWER' as AgentRole,
    status: 'IDLE',
    enabled: true,
    capabilities: {
      planning: false,
      coding: false,
      testing: false,
      reviewing: true,
      security: true,
      orchestration: false,
    },
    preferredProfile: 'review',
    preferredModel: 'default',
    loadFactor: 0,
    createdAt: NOW,
    updatedAt: NOW,
  },
];
